apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  gameServerTemplate:
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: minecraft
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 100%
  network:
    networkType: AlibabaCloud-SLB
    networkConf:
      - name: SlbIds
        value: {{ .Values.network.slbIds }}
      - name: PortProtocols
        value: "25565"
      - name: Fixed
        value: "false"
  serviceQualities: # 设置了一个idle的服务质量
    - name: healthy
      containerName: minecraft
      permanent: false
      exec:
        command: ["bash", "./healthy.sh"]
      serviceQualityAction:
        - state: false
          opsState: Maintaining
        - state: true
          opsState: None
    - name: idle
      containerName: minecraft
      initialDelaySeconds: 10
      permanent: false
      exec:
        command: [ "bash", "./idle.sh" ]
      serviceQualityAction:
        - state: true
          opsState: WaitToBeDeleted
        - state: false
          opsState: None